/* This file was generated by syncqt. */
#ifndef QT_QTOPENGL_VERSION_H
#define QT_QTOPENGL_VERSION_H

#define QTOPENGL_VERSION_STR "6.11.2"

#define QTOPENGL_VERSION 0x0601102

#endif // QT_QTOPENGL_VERSION_H
