/* This file was generated by syncqt. */
#ifndef QT_QTOPENGL_VERSION_H
#define QT_QTOPENGL_VERSION_H

#define QTOPENGL_VERSION_STR "6.12.0"

#define QTOPENGL_VERSION 0x0601200

#endif // QT_QTOPENGL_VERSION_H
