/**
 * @file Simulation/Simulation.h
 * Declaration of class Simulation
 * @author Colin Graf
 */

#pragma once

#include "Graphics/GraphicsContext.h"
#include "Simulation/Appearances/ComplexAppearance.h"
#include <mujoco/mjdata.h>
#include <mujoco/mjmodel.h>
#include <mujoco/mjspec.h>
#include <string>
#include <list>
#include <unordered_map>

class Body;
class Geometry;
class Scene;
class ElementCore3;

/**
 * @class Simulation
 * A class for managing the simulation
 */
class Simulation
{
public:
  static Simulation* simulation;

  Scene* scene = nullptr; /**< The root of the scene graph */
  std::list<ElementCore3*> elements; /**< All scene graph elements */

  mjSpec* spec = nullptr; /**< The model specification that is built from the scene description. Only valid during \c createPhysics. */
  mjsBody* worldBody = nullptr; /**< The world (root) body in the model specification. Only valid during \c createPhysics. */
  mjModel* model = nullptr; /**< The MuJoCo model that is compiled from the model specification. Only valid after \c createPhysics. */
  mjData* data = nullptr; /**< The MuJoCo simulation state. Only valid after \c createPhysics. */
  std::vector<Body*> bodyMap; /**< A map from body index in \c data to the SimRobot object. */
  std::vector<Geometry*> geometryMap; /**< A map from geom index in \c data to the SimRobot object. */

  GraphicsContext graphicsContext; /**< The object that does graphics. */
  GraphicsContext::Mesh* xAxisMesh = nullptr; /**< The mesh for the x axis in object renderers. */
  GraphicsContext::Mesh* yAxisMesh = nullptr; /**< The mesh for the y axis in object renderers. */
  GraphicsContext::Mesh* zAxisMesh = nullptr; /**< The mesh for the z axis in object renderers. */
  GraphicsContext::Mesh* dragPlaneMesh = nullptr; /**< The mesh for the drag plane in object renderers. */
  GraphicsContext::Mesh* bodyComSphereMesh = nullptr; /**< The mesh for the physical CoM drawing of bodies. */
  GraphicsContext::Surface* xAxisSurface = nullptr; /**< The surface for the x axis in object renderers. */
  GraphicsContext::Surface* yAxisSurface = nullptr; /**< The surface for the y axis in object renderers. */
  GraphicsContext::Surface* zAxisSurface = nullptr; /**< The surface for the z axis in object renderers. */
  GraphicsContext::Surface* dragPlaneSurface = nullptr; /**< The surface for the drag plane in object renderers. */
  GraphicsContext::Surface* bodyComSphereSurface = nullptr; /**< The surface for the physical CoM drawing of bodies. */
  GraphicsContext::ModelMatrix* originModelMatrix = nullptr; /**< The model matrix for the origin in object renderers. */
  GraphicsContext::ModelMatrix* dragPlaneModelMatrix = nullptr; /**< The model matrix for the drag plane in object renderers. */
  Pose3f originPose; /**< Pose of the origin (assuming that renderers are sequential. */
  Pose3f dragPlanePose; /**< Pose of the drag plane (assuming it is not possible to drag simultaneously in multiple renderers). */
  std::vector<GraphicsContext::Surface*> bodySurfaces; /**< The special surfaces for each body, used by \c ObjectSegmentedImageSensor. */
  std::unordered_map<ComplexAppearance::Descriptor, GraphicsContext::Mesh*, ComplexAppearance::Hasher> complexAppearanceMeshCache; /**< The cache for meshes generated by complex appearances. */

  unsigned int currentFrameRate = 0; /**< The current frame rate of the simulation */

  /** Default Constructor. */
  Simulation();

  /** Destructor. */
  virtual ~Simulation();

  /**
   * Loads a file and initializes the simulation
   * @param filename The name of the file
   * @param errors The errors that occurred during parsing.
   */
  bool loadFile(const std::string& filename, std::list<std::string>& errors);

  /**
   * Creates a unique name for a MuJoCo element and registers it so its index can be obtained later.
   * @param type The MuJoCo object type.
   * @param prefix A prefix from which the name is constructed.
   * @param indexPointer Pointer which is later filled by the index that MuJoCo assigned to the object.
   * @param object Pointer to the SimRobot object.
   * @return A name to be used with \c mjs_setName.
   */
  const char* getName(int type, const char* prefix, int* indexPointer = nullptr, void* object = nullptr)
  {
    static int counter = 0;
    const std::string name = std::string(prefix) + "_" + std::to_string(counter++);
    names.emplace_back(type, name, indexPointer, object);
    return names.back().name.c_str();
  }

  /** Executes one simulation step */
  void doSimulationStep();
  unsigned int simulationStep = 0;
  double simulatedTime = 0;
  unsigned int collisions = 0;
  unsigned int contactPoints = 0;

  /** Registers all objects of the simulation (including children, actuators and sensors) at SimRobot's GUI */
  void registerObjects();

private:
  /** Computes the frame rate of simulation */
  void updateFrameRate();
  unsigned int lastFrameRateComputationTime = 0;
  unsigned int lastFrameRateComputationStep = 0;

  struct RegisteredName
  {
    int type = -1; /**< The MuJoCo object type. */
    std::string name; /**< The name of the object. */
    int* indexPointer = nullptr; /**< Pointer which is later filled by the index that MuJoCo assigned to the object. */
    void* object = nullptr; /**< Pointer to the (SimRobot) object (used to map from the MuJoCo index to the object). */
  };
  std::list<RegisteredName> names; /**< The registered names of MuJoCo objects. */
};
