#!/bin/bash
# Generate CLion project or CMake caches

cd "$(dirname "$(which "$0")")"

if [ -n "$NO_CLION" ]; then
  for CONFIG in Debug Develop Release; do
    cmake -DCMAKE_BUILD_TYPE=$CONFIG -G Ninja -S . -B ../../Build/Linux/CMake/$CONFIG
  done
else
  CMAKE_RUN_CONFIGURATION_MANAGER="    <generated>
      <config projectName=\"SimRobot\" targetName=\"SimRobot\" />
    </generated>"

  CMAKE_SETTINGS="    <configurations>
      <configuration PROFILE_NAME=\"Debug\" CONFIG_NAME=\"Debug\" GENERATION_OPTIONS=\"-G Ninja\" GENERATION_DIR=\"../../Build/Linux/CMake/Debug\" BUILD_OPTIONS=\"\" />
      <configuration PROFILE_NAME=\"Develop\" CONFIG_NAME=\"Develop\" GENERATION_OPTIONS=\"-G Ninja\" GENERATION_DIR=\"../../Build/Linux/CMake/Develop\" BUILD_OPTIONS=\"\" />
      <configuration PROFILE_NAME=\"Release\" CONFIG_NAME=\"Release\" GENERATION_OPTIONS=\"-G Ninja\" GENERATION_DIR=\"../../Build/Linux/CMake/Release\" BUILD_OPTIONS=\"\" />
    </configurations>"

  RUN_MANAGER="    <configuration name=\"SimRobot\" type=\"CMakeRunConfiguration\" factoryName=\"Application\" PASS_PARENT_ENVS_2=\"true\" PROJECT_NAME=\"SimRobot\" TARGET_NAME=\"SimRobot\" CONFIG_NAME=\"Debug\" RUN_TARGET_PROJECT_NAME=\"SimRobot\" RUN_TARGET_NAME=\"SimRobot\">
      <method v=\"2\">
        <option name=\"com.jetbrains.cidr.execution.CidrBuildBeforeRunTaskProvider\$BuildBeforeRunTask\" enabled=\"true\" />
      </method>
    </configuration>
    <list>
      <item itemvalue=\"CMake Application.SimRobot\" />
    </list>"

  if [ -e .idea/workspace.xml ]; then
    (
      sed -n "/<component name=\"CMakeRunConfigurationManager\"/{p;:a;N;/<\/component>\$/!ba;c\\
$((tr '\n' '@' | sed 's/@/\\\n/g') <<<$CMAKE_RUN_CONFIGURATION_MANAGER)
\
  <\/component>
};p" |
      sed -n "/<component name=\"CMakeSettings\"/{p;:a;N;/<\/component>\$/!ba;c\\
$((tr '\n' '@' | sed 's/@/\\\n/g') <<<$CMAKE_SETTINGS)
\
  <\/component>
};p" |
      sed -n "/<component name=\"RunManager\"/{p;:a;N;/<\/component>\$/!ba;c\\
$((tr '\n' '@' | sed 's/@/\\\n/g') <<<$RUN_MANAGER)
\
  <\/component>
};p"
    ) <.idea/workspace.xml >.idea/temp.xml && mv .idea/temp.xml .idea/workspace.xml
  else
    echo >.idea/workspace.xml "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<project version=\"4\">
  <component name=\"CMakeRunConfigurationManager\" shouldGenerate=\"false\" shouldDeleteObsolete=\"false\">
$CMAKE_RUN_CONFIGURATION_MANAGER
  </component>
  <component name=\"CMakeSettings\">
    <configurations>
$CMAKE_SETTINGS
    </configurations>
  </component>
  <component name=\"RunManager\" selected=\"CMake Application.SimRobot\">
$RUN_MANAGER
  </component>
</project>"
  fi
fi
